// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/etcd-discovery/v7/service (interfaces: ServiceResponse)

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	service "github.com/Scalingo/etcd-discovery/v7/service"
)

// MockServiceResponse is a mock of ServiceResponse interface.
type MockServiceResponse struct {
	ctrl     *gomock.Controller
	recorder *MockServiceResponseMockRecorder
	isgomock struct{}
}

// MockServiceResponseMockRecorder is the mock recorder for MockServiceResponse.
type MockServiceResponseMockRecorder struct {
	mock *MockServiceResponse
}

// NewMockServiceResponse creates a new mock instance.
func NewMockServiceResponse(ctrl *gomock.Controller) *MockServiceResponse {
	mock := &MockServiceResponse{ctrl: ctrl}
	mock.recorder = &MockServiceResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceResponse) EXPECT() *MockServiceResponseMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockServiceResponse) All(ctx context.Context) (service.Hosts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].(service.Hosts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockServiceResponseMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockServiceResponse)(nil).All), ctx)
}

// Err mocks base method.
func (m *MockServiceResponse) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockServiceResponseMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockServiceResponse)(nil).Err))
}

// First mocks base method.
func (m *MockServiceResponse) First(ctx context.Context) service.HostResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", ctx)
	ret0, _ := ret[0].(service.HostResponse)
	return ret0
}

// First indicates an expected call of First.
func (mr *MockServiceResponseMockRecorder) First(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockServiceResponse)(nil).First), ctx)
}

// One mocks base method.
func (m *MockServiceResponse) One(ctx context.Context) service.HostResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "One", ctx)
	ret0, _ := ret[0].(service.HostResponse)
	return ret0
}

// One indicates an expected call of One.
func (mr *MockServiceResponseMockRecorder) One(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "One", reflect.TypeOf((*MockServiceResponse)(nil).One), ctx)
}

// Service mocks base method.
func (m *MockServiceResponse) Service(ctx context.Context) (*service.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Service", ctx)
	ret0, _ := ret[0].(*service.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Service indicates an expected call of Service.
func (mr *MockServiceResponseMockRecorder) Service(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Service", reflect.TypeOf((*MockServiceResponse)(nil).Service), ctx)
}

// URL mocks base method.
func (m *MockServiceResponse) URL(ctx context.Context, scheme, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL", ctx, scheme, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URL indicates an expected call of URL.
func (mr *MockServiceResponseMockRecorder) URL(ctx, scheme, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockServiceResponse)(nil).URL), ctx, scheme, path)
}
