// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/etcd-discovery/v7/service (interfaces: HostResponse)

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"

	service "github.com/Scalingo/etcd-discovery/v7/service"
	gomock "go.uber.org/mock/gomock"
)

// MockHostResponse is a mock of HostResponse interface.
type MockHostResponse struct {
	ctrl     *gomock.Controller
	recorder *MockHostResponseMockRecorder
	isgomock struct{}
}

// MockHostResponseMockRecorder is the mock recorder for MockHostResponse.
type MockHostResponseMockRecorder struct {
	mock *MockHostResponse
}

// NewMockHostResponse creates a new mock instance.
func NewMockHostResponse(ctrl *gomock.Controller) *MockHostResponse {
	mock := &MockHostResponse{ctrl: ctrl}
	mock.recorder = &MockHostResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostResponse) EXPECT() *MockHostResponseMockRecorder {
	return m.recorder
}

// Err mocks base method.
func (m *MockHostResponse) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockHostResponseMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockHostResponse)(nil).Err))
}

// Host mocks base method.
func (m *MockHostResponse) Host(ctx context.Context) (*service.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Host", ctx)
	ret0, _ := ret[0].(*service.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Host indicates an expected call of Host.
func (mr *MockHostResponseMockRecorder) Host(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Host", reflect.TypeOf((*MockHostResponse)(nil).Host), ctx)
}

// PrivateURL mocks base method.
func (m *MockHostResponse) PrivateURL(ctx context.Context, scheme, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateURL", ctx, scheme, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivateURL indicates an expected call of PrivateURL.
func (mr *MockHostResponseMockRecorder) PrivateURL(ctx, scheme, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateURL", reflect.TypeOf((*MockHostResponse)(nil).PrivateURL), ctx, scheme, path)
}

// URL mocks base method.
func (m *MockHostResponse) URL(ctx context.Context, scheme, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL", ctx, scheme, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URL indicates an expected call of URL.
func (mr *MockHostResponseMockRecorder) URL(ctx, scheme, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockHostResponse)(nil).URL), ctx, scheme, path)
}
